linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - godox
    - goerr113
    - gomnd
    - ireturn
    - nestif
    - nlreturn
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck

    # Deprecated linters
    - deadcode
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  govet:
    check-shadowing: true
  gci:
    local-prefixes: github.com/belak/go-gitdir
  tagliatelle:
    case:
      rules:
        yaml: snake
