language: go
go:
  #- '1.12'
  - stable
env:
  - GO111MODULE=on

before_install:
  - GO111MODULE=off go get -u github.com/Quasilyte/go-consistent
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  # Test
  - go test -v ./...

   # Linting
  - golangci-lint run
  - go-consistent ./...
