# Build and deploy steps:
#
# 01. On the host machine, run
#     `RUID=gitdir RGID=gitdir docker-compose --compatibility build gitdir`
# 02. Then `docker volume create gitdir`
# 03. Follow by `RUID=gitdir RGID=gitdir docker-compose --compatibility up -d`,
#     a container named `gitdir` should start
# 04. If this is the first time you deploy `gitdir` in this method, run
#     `docker exec -it gitdir gitdir_config` to initialize it
# 05. Command `gitdir_config` will wait for `gitdir` to load, this may take
#     few minutes. You can checkout `docker logs gitdir` for the progress (the
#     wait usually ends when "Starting SSH server" is logged)
# 06. After `gitdir` is loaded, `gitdir_config` will automatically open
#     `config.yml` for you to edit. Make sure to add yourself as the admin by
#     creating an new item under `users`, for example:
#     users:
#       <username,replacewithyourown>:
#         is_admin: true
#         disabled: false
#         keys:
#           - <Your SSH public key, the one in ~/.ssh/id_ed25519.pub for example>
#     Watch out for the format, Use SPACE instead of tab so the yaml file
#     remain valid.
#     Save the file by pressing ESC and then type :wq
# 07. Create commit information, and then ESC + :wq as above
# 08. If you see "Saved!" message, run `docker restart gitdir` to restart
#     `gitdir`. Otherwise, please checkout the output to see what wrong, and
#     maybe try step 6 again
# 09. After `gitdir` restarts, you may try
#     `git clone ssh://<your_username>@<gitdir_host>:2222/admin.git`
#     to clone the admin repository of gitdir
# 10. To learn how to create repository and more, see the home page of `gitdir`
#
# Note: RGID and RUID defines which user `gitdir` will be run under. Checkout
#       related Docker documentation for detail
version: "3.7"

volumes:
  gitdir:
    external: true

services:
  gitdir:
    image: gitdir-localbuilt
    container_name: gitdir
    user: "${RUID}:${RGID}"
    build: .
    restart: unless-stopped
    ports:
      - "0.0.0.0:2222:2222/tcp"
    stdin_open: true
    volumes:
      - gitdir:/var/gitdir
    tty: true
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
